# Generated by Django 3.2.7 on 2022-10-12 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdetails',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
