# Generated by Django 3.2.7 on 2022-10-11 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_property_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.TextField(default='text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserve',
            name='phone_number',
            field=models.CharField(default='exit', max_length=15),
            preserve_default=False,
        ),
    ]
