# Generated by Django 3.2.7 on 2022-10-12 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_auto_20221012_0416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='property',
            name='image2',
            field=models.ImageField(null=True, upload_to='property/'),
        ),
        migrations.AddField(
            model_name='property',
            name='image3',
            field=models.ImageField(null=True, upload_to='property/'),
        ),
    ]
