# Generated by Django 3.2.7 on 2022-10-12 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_rename_image3_property_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='property',
            name='image2',
        ),
    ]
